### ISSUE TITLE
Make it possible to implement custom filters

### ISSUE THREAD

**Issue by cwdt** [onemustcode/query#1]
Would it be possible to extend the DoctrineQueryBuilder to allow custom (user-space) filters, this is currently not possible since the DoctrineQueryBuilder is fairly limited by the switch-case statement?
 
If appreciated I would want to create a pull request for this functionality.

**Comment by blackvault-bv** [comment]
Hey @cwdt,

Sorry for the late reply, but apparently Github doesn't send me any notifications..

But, yea! If you can make an proposal on how you want to implement this. Maybe register custom filters on the doctrine query builder instead of just extending the doctrine query builder? More flexible.

**Comment by blackvault-bv** [comment]
See #5

**Comment by cwdt** [comment]
Thanks @onemustcode!
